-- Durable SSE event history shared by all application workers.
-- Run once in the Supabase SQL editor before enabling cross-worker SSE.

create table if not exists sse_events (
  id bigint generated by default as identity primary key,
  job_id text not null,
  event_data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists sse_events_job_id_id_idx
  on sse_events (job_id, id);

create index if not exists sse_events_created_at_idx
  on sse_events (created_at);

alter table sse_events enable row level security;
